/*
 * Copyright (c) 2026 L. Ledoux
 * SPDX-License-Identifier: Apache-2.0
 */

`default_nettype none

module tt_um_lledoux_s3fdp_seqcomb (
    input  wire [7:0] ui_in,
    output logic [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);

  localparam logic [1:0] ST_LOAD = 2'd0;
  localparam logic [1:0] ST_RUN  = 2'd1;
  localparam logic [1:0] ST_OUT  = 2'd2;

  localparam logic [4:0] FRAME_LAST = 5'd19;
  localparam logic [2:0] RUN_LATENCY_CYCLES = 3'd3;

  logic [1:0] state;
  logic [4:0] load_idx;
  logic [2:0] run_count;
  logic [1:0] out_idx;

  logic [31:0] a_words [0:1];
  logic [31:0] b_words [0:1];
  logic [31:0] c0_word;
  logic [31:0] result_word;

  logic [1:0][31:0] core_a;
  logic [1:0][31:0] core_b;
  logic [1:0][31:0] core_c;
  logic core_reset;
  logic [31:0] core_r;

  always @(*) begin
    core_a[0] = a_words[0];
    core_a[1] = a_words[1];
    core_b[0] = b_words[0];
    core_b[1] = b_words[1];
    core_c[0] = c0_word;
    core_c[1] = 32'h00000000;
  end

  assign core_reset = (~rst_n) | (state == ST_LOAD);

  fpmult_loop_muladd_s3fdp s3fdp_core (
      .clk(clk),
      .reset(core_reset),
      .a(core_a),
      .b(core_b),
      .c(core_c),
      .clk_0(clk),
      .r(core_r)
  );

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_LOAD;
      load_idx <= '0;
      run_count <= '0;
      out_idx <= '0;
      a_words[0] <= '0;
      a_words[1] <= '0;
      b_words[0] <= '0;
      b_words[1] <= '0;
      c0_word <= '0;
      result_word <= '0;
    end else if (ena) begin
      case (state)
        ST_LOAD: begin
          case (load_idx)
            5'd0:  a_words[0][7:0]   <= ui_in;
            5'd1:  a_words[0][15:8]  <= ui_in;
            5'd2:  a_words[0][23:16] <= ui_in;
            5'd3:  a_words[0][31:24] <= ui_in;
            5'd4:  a_words[1][7:0]   <= ui_in;
            5'd5:  a_words[1][15:8]  <= ui_in;
            5'd6:  a_words[1][23:16] <= ui_in;
            5'd7:  a_words[1][31:24] <= ui_in;
            5'd8:  b_words[0][7:0]   <= ui_in;
            5'd9:  b_words[0][15:8]  <= ui_in;
            5'd10: b_words[0][23:16] <= ui_in;
            5'd11: b_words[0][31:24] <= ui_in;
            5'd12: b_words[1][7:0]   <= ui_in;
            5'd13: b_words[1][15:8]  <= ui_in;
            5'd14: b_words[1][23:16] <= ui_in;
            5'd15: b_words[1][31:24] <= ui_in;
            5'd16: c0_word[7:0]      <= ui_in;
            5'd17: c0_word[15:8]     <= ui_in;
            5'd18: c0_word[23:16]    <= ui_in;
            5'd19: c0_word[31:24]    <= ui_in;
            default: ;
          endcase

          if (load_idx == FRAME_LAST) begin
            state <= ST_RUN;
            run_count <= '0;
          end else begin
            load_idx <= load_idx + 5'd1;
          end
        end

        ST_RUN: begin
          if (run_count == (RUN_LATENCY_CYCLES - 3'd1)) begin
            result_word <= core_r;
            state <= ST_OUT;
            out_idx <= '0;
          end else begin
            run_count <= run_count + 3'd1;
          end
        end

        ST_OUT: begin
          if (out_idx == 2'd3) begin
            state <= ST_LOAD;
            load_idx <= '0;
            a_words[0] <= '0;
            a_words[1] <= '0;
            b_words[0] <= '0;
            b_words[1] <= '0;
            c0_word <= '0;
          end else begin
            out_idx <= out_idx + 2'd1;
          end
        end

        default: begin
          state <= ST_LOAD;
          load_idx <= '0;
          run_count <= '0;
          out_idx <= '0;
        end
      endcase
    end
  end

  always @(*) begin
    if (state == ST_OUT) begin
      case (out_idx)
        2'd0: uo_out = result_word[7:0];
        2'd1: uo_out = result_word[15:8];
        2'd2: uo_out = result_word[23:16];
        2'd3: uo_out = result_word[31:24];
        default: uo_out = 8'h00;
      endcase
    end else begin
      uo_out = 8'h00;
    end
  end

  assign uio_out = 8'h00;
  assign uio_oe  = 8'h00;

  wire _unused = &{uio_in, 1'b0};

endmodule
// Generated by CIRCT 30ab7a85a
module fpmult_loop_muladd_s3fdp(
  input              clk,
                     reset,
  input  [1:0][31:0] a,
                     b,
                     c,
  input              clk_0,
  output [31:0]      r
);

  wire [31:0] _GEN;
  wire [31:0] _GEN_0;
  wire [31:0] _GEN_1;
  wire        _GEN_2;
  wire [63:0] _GEN_3 = /*cast(bit[63:0])*/b;
  wire [63:0] _GEN_4 = /*cast(bit[63:0])*/a;
  reg  [31:0] c_mem[0:1];
  always_ff @(posedge clk_0) begin
    if (reset) begin
    end
    else begin
      if (_GEN_2)
        c_mem[1'h0] <= _GEN_0;
    end
  end // always_ff @(posedge)
  reg  [31:0] _GEN_5;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_5 <= 32'h0;
    else
      _GEN_5 <= _GEN;
  end // always_ff @(posedge)
  assign _GEN_2 = _GEN_5 == 32'h0;
  reg  [31:0] _GEN_6;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_6 <= 32'h0;
    else
      _GEN_6 <= _GEN_1;
  end // always_ff @(posedge)
  wire        _GEN_7 = _GEN_6 == 32'h1;
  assign _GEN_1 = _GEN_2 ? (_GEN_7 ? 32'h0 : _GEN_6 + 32'h1) : _GEN_6;
  wire [31:0] _GEN_8 = _GEN_6[0] ? _GEN_4[63:32] : _GEN_4[31:0];
  wire [31:0] _GEN_9 = _GEN_6[0] ? _GEN_3[63:32] : _GEN_3[31:0];
  wire        _GEN_10 = _GEN_8[30:23] == 8'h0;
  wire        _GEN_11 = &(_GEN_8[30:23]);
  wire        _GEN_12 = _GEN_8[22:0] == 23'h0;
  wire        _GEN_13 = _GEN_9[30:23] == 8'h0;
  wire        _GEN_14 = &(_GEN_9[30:23]);
  wire        _GEN_15 = _GEN_9[22:0] == 23'h0;
  wire [47:0] _GEN_16 =
    {25'h1, _GEN_10 & _GEN_8[22] ? {_GEN_8[21:0], 1'h0} : _GEN_8[22:0]}
    * {25'h1, _GEN_13 & _GEN_9[22] ? {_GEN_9[21:0], 1'h0} : _GEN_9[22:0]};
  wire [9:0]  _GEN_17 =
    {2'h0, _GEN_8[30:23]} + {2'h0, _GEN_9[30:23]} + {9'h0, _GEN_16[47]} - 10'h7F;
  wire [3:0]  _GEN_18 =
    {_GEN_10 & ~(_GEN_8[22])
       ? 2'h0
       : _GEN_11 & _GEN_12 ? 2'h2 : {_GEN_11 & ~_GEN_12, 1'h1},
     _GEN_13 & ~(_GEN_9[22])
       ? 2'h0
       : _GEN_14 & _GEN_15 ? 2'h2 : {_GEN_14 & ~_GEN_15, 1'h1}};
  wire [1:0]  _GEN_19 =
    _GEN_18 == 4'h6 | _GEN_18 == 4'h9 | _GEN_18 == 4'hA
      ? 2'h2
      : _GEN_18 == 4'h5
          ? 2'h1
          : _GEN_18 == 4'h0 | _GEN_18 == 4'h1 | _GEN_18 == 4'h4 ? 2'h0 : 2'h3;
  wire [1:0]  _GEN_20 =
    _GEN_19 == 2'h1
      ? (_GEN_17[9:8] == 2'h2 | (&(_GEN_17[9:8]))
           ? 2'h0
           : _GEN_17[9:8] == 2'h1 ? 2'h2 : {|(_GEN_17[9:8]), 1'h1})
      : _GEN_19;
  wire [46:0] _GEN_21 = _GEN_16[47] ? _GEN_16[46:0] : {_GEN_16[45:0], 1'h0};
  wire        _GEN_22 = _GEN_20 == 2'h0;
  wire        _GEN_23 = _GEN_20 == 2'h1;
  wire [46:0] _GEN_24 = _GEN_17[7:0] == 8'h0 & _GEN_23 ? {1'h1, _GEN_21[46:1]} : _GEN_21;
  wire [30:0] _GEN_25 =
    {_GEN_17[7:0], _GEN_24[46:24]}
    + {30'h0, _GEN_24[23] & ((|(_GEN_24[22:0])) | _GEN_24[24])};
  wire [22:0] _GEN_26 = _GEN_22 ? 23'h0 : _GEN_23 ? _GEN_25[22:0] : {22'h0, _GEN_20[0]};
  wire [7:0]  _GEN_27 = _GEN_22 ? 8'h0 : _GEN_23 ? _GEN_25[30:23] : 8'hFF;
  wire        _GEN_28 = c_mem[1'h0][30:23] == 8'h0;
  wire        _GEN_29 = &(c_mem[1'h0][30:23]);
  wire        _GEN_30 = c_mem[1'h0][22:0] == 23'h0;
  wire [22:0] _GEN_31 =
    _GEN_28 & c_mem[1'h0][22] ? {c_mem[1'h0][21:0], 1'h0} : c_mem[1'h0][22:0];
  wire [1:0]  _GEN_32 =
    _GEN_28 & ~(c_mem[1'h0][22])
      ? 2'h0
      : _GEN_29 & _GEN_30 ? 2'h2 : {_GEN_29 & ~_GEN_30, 1'h1};
  wire [33:0] _GEN_33 = {_GEN_32, c_mem[1'h0][31:23], _GEN_31};
  wire        _GEN_34 = _GEN_27 == 8'h0;
  wire        _GEN_35 = &_GEN_27;
  wire        _GEN_36 = _GEN_26 == 23'h0;
  wire [22:0] _GEN_37 = _GEN_34 & _GEN_26[22] ? {_GEN_26[21:0], 1'h0} : _GEN_26;
  wire [1:0]  _GEN_38 =
    _GEN_34 & ~(_GEN_26[22])
      ? 2'h0
      : _GEN_35 & _GEN_36 ? 2'h2 : {_GEN_35 & ~_GEN_36, 1'h1};
  wire [33:0] _GEN_39 =
    {_GEN_38,
     (_GEN_23 | _GEN_20 == 2'h2 | _GEN_22) & (_GEN_8[31] ^ _GEN_9[31]),
     _GEN_27,
     _GEN_37};
  wire        _GEN_40 =
    {_GEN_32, c_mem[1'h0][30:23], _GEN_31} < {_GEN_38, _GEN_27, _GEN_37};
  wire [7:0]  _GEN_41 =
    _GEN_40 ? _GEN_27 - c_mem[1'h0][30:23] : c_mem[1'h0][30:23] - _GEN_27;
  wire [33:0] _GEN_42 = _GEN_40 ? _GEN_39 : _GEN_33;
  wire [33:0] _GEN_43 = _GEN_40 ? _GEN_33 : _GEN_39;
  wire        _GEN_44 = _GEN_42[31] ^ _GEN_43[31];
  wire [5:0]  _GEN_45 = {_GEN_42[31], _GEN_43[31], _GEN_42[33:32], _GEN_43[33:32]};
  wire [23:0] _GEN_46 = _GEN_43[33:32] == 2'h0 ? 24'h0 : {1'h1, _GEN_43[22:0]};
  wire        _GEN_47 = _GEN_45 == 6'h10;
  wire        _GEN_48 = _GEN_45 == 6'h20;
  wire [1:0]  _GEN_49 =
    _GEN_45 == 6'h3A | _GEN_45 == 6'hA | _GEN_45 == 6'h8 | _GEN_45 == 6'h18
    | _GEN_45 == 6'h28 | _GEN_45 == 6'h38 | _GEN_45 == 6'h2 | _GEN_45 == 6'h12
    | _GEN_45 == 6'h22 | _GEN_45 == 6'h32 | _GEN_45 == 6'h9 | _GEN_45 == 6'h19
    | _GEN_45 == 6'h29 | _GEN_45 == 6'h39 | _GEN_45 == 6'h6 | _GEN_45 == 6'h16
    | _GEN_45 == 6'h26 | _GEN_45 == 6'h36
      ? 2'h2
      : _GEN_45 == 6'h5 | _GEN_45 == 6'h15 | _GEN_45 == 6'h25 | _GEN_45 == 6'h35
        | _GEN_45 == 6'h4 | _GEN_45 == 6'h14 | _GEN_45 == 6'h24 | _GEN_45 == 6'h34
        | _GEN_45 == 6'h1 | _GEN_45 == 6'h11 | _GEN_45 == 6'h21 | _GEN_45 == 6'h31
          ? 2'h1
          : _GEN_45 == 6'h0 | _GEN_47 | _GEN_48 | _GEN_45 == 6'h30 ? 2'h0 : 2'h3;
  wire [4:0]  _GEN_50 = _GEN_41 > 8'h19 ? 5'h1A : _GEN_41[4:0];
  wire [25:0] _GEN_51 = _GEN_50[4] ? {16'h0, _GEN_46[23:14]} : {_GEN_46, 2'h0};
  wire [25:0] _GEN_52 = _GEN_50[3] ? {8'h0, _GEN_51[25:8]} : _GEN_51;
  wire [25:0] _GEN_53 = _GEN_50[2] ? {4'h0, _GEN_52[25:4]} : _GEN_52;
  wire [25:0] _GEN_54 = _GEN_50[1] ? {2'h0, _GEN_53[25:2]} : _GEN_53;
  wire        _GEN_55 =
    _GEN_50[4] & (|(_GEN_46[13:0])) | _GEN_50[3] & (|(_GEN_51[7:0])) | _GEN_50[2]
    & (|(_GEN_52[3:0])) | _GEN_50[1] & (|(_GEN_53[1:0])) | _GEN_50[0] & _GEN_54[0];
  wire [26:0] _GEN_56 =
    {2'h1, _GEN_42[22:0], 2'h0}
    + ({1'h0, _GEN_50[0] ? {1'h0, _GEN_54[25:1]} : _GEN_54} ^ {27{_GEN_44}})
    + {26'h0, _GEN_44 & ~_GEN_55};
  wire        _GEN_57 = _GEN_56[26:11] == 16'h0;
  wire [27:0] _GEN_58 = _GEN_57 ? {_GEN_56[10:0], _GEN_55, 16'h0} : {_GEN_56, _GEN_55};
  wire        _GEN_59 = _GEN_58[27:20] == 8'h0;
  wire [27:0] _GEN_60 = _GEN_59 ? {_GEN_58[19:0], 8'h0} : _GEN_58;
  wire        _GEN_61 = _GEN_60[27:24] == 4'h0;
  wire [27:0] _GEN_62 = _GEN_61 ? {_GEN_60[23:0], 4'h0} : _GEN_60;
  wire        _GEN_63 = _GEN_62[27:26] == 2'h0;
  wire [27:0] _GEN_64 = _GEN_63 ? {_GEN_62[25:0], 2'h0} : _GEN_62;
  wire        _GEN_65 = ~(_GEN_64[27]);
  wire [26:0] _GEN_66 = _GEN_65 ? {_GEN_64[25:0], 1'h0} : _GEN_64[26:0];
  wire        _GEN_67 = &{_GEN_57, _GEN_59, _GEN_61, _GEN_63, _GEN_65};
  wire        _GEN_68 = _GEN_66[2] | _GEN_66[1] | _GEN_66[0];
  wire [33:0] _GEN_69 =
    {{1'h0, {1'h0, _GEN_42[30:23]} + 9'h1}
       - {5'h0, _GEN_57, _GEN_59, _GEN_61, _GEN_63, _GEN_65},
     _GEN_66[26:3]} + {33'h0, _GEN_66[3] & _GEN_68 | _GEN_66[3] & ~_GEN_68 & _GEN_66[4]};
  wire [3:0]  _GEN_70 = {_GEN_69[33:32], _GEN_49};
  wire [1:0]  _GEN_71 =
    _GEN_67 & _GEN_44 & _GEN_49 != 2'h3
      ? 2'h0
      : _GEN_70 == 4'h2 | _GEN_70 == 4'h6 | _GEN_70 == 4'hA | _GEN_70 == 4'hE
        | _GEN_70 == 4'h5
          ? 2'h2
          : _GEN_70 == 4'h1
              ? 2'h1
              : _GEN_70 == 4'h0 | _GEN_70 == 4'h4 | _GEN_70 == 4'h8 | _GEN_70 == 4'hC
                | _GEN_70 == 4'h9 | _GEN_70 == 4'hD
                  ? 2'h0
                  : 2'h3;
  wire        _GEN_72 = _GEN_71 == 2'h0;
  wire        _GEN_73 = _GEN_71 == 2'h1;
  assign _GEN_0 =
    {(_GEN_73 | _GEN_71 == 2'h2 | _GEN_72) & ~(_GEN_67 & _GEN_44) & ~(_GEN_48 | _GEN_47)
       & _GEN_42[31],
     _GEN_72 ? 8'h0 : _GEN_73 ? _GEN_69[31:24] : 8'hFF,
     _GEN_72
       ? 23'h0
       : _GEN_69[31:24] == 8'h0 & _GEN_73
           ? {1'h1, _GEN_69[23:2]}
           : _GEN_73 ? _GEN_69[23:1] : {22'h0, _GEN_71[0]}};
  assign _GEN = _GEN_2 & _GEN_7 ? 32'h0 : _GEN_5;
  assign r = c_mem[1'h0];
endmodule

