/*
 * Copyright (c) 2026 L. Ledoux
 * SPDX-License-Identifier: Apache-2.0
 */

`default_nettype none

module tt_um_lledoux_s3fdp_seqcomb (
    input  wire [7:0] ui_in,
    output logic [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);

  localparam logic [1:0] ST_LOAD = 2'd0;
  localparam logic [1:0] ST_RUN  = 2'd1;
  localparam logic [1:0] ST_OUT  = 2'd2;

  localparam logic [4:0] FRAME_LAST = 5'd19;
  localparam logic [2:0] RUN_LATENCY_CYCLES = 3'd3;

  logic [1:0] state;
  logic [4:0] load_idx;
  logic [2:0] run_count;
  logic [1:0] out_idx;

  logic [31:0] a_words [0:1];
  logic [31:0] b_words [0:1];
  logic [31:0] c0_word;
  logic [31:0] result_word;

  logic [1:0][31:0] core_a;
  logic [1:0][31:0] core_b;
  logic [1:0][31:0] core_c;
  logic core_reset;
  logic [31:0] core_r;

  always @(*) begin
    core_a[0] = a_words[0];
    core_a[1] = a_words[1];
    core_b[0] = b_words[0];
    core_b[1] = b_words[1];
    core_c[0] = c0_word;
    core_c[1] = 32'h00000000;
  end

  assign core_reset = (~rst_n) | (state == ST_LOAD);

  fpmult_loop_muladd_s3fdp s3fdp_core (
      .clk(clk),
      .reset(core_reset),
      .a(core_a),
      .b(core_b),
      .c(core_c),
      .clk_0(clk),
      .r(core_r)
  );

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_LOAD;
      load_idx <= '0;
      run_count <= '0;
      out_idx <= '0;
      a_words[0] <= '0;
      a_words[1] <= '0;
      b_words[0] <= '0;
      b_words[1] <= '0;
      c0_word <= '0;
      result_word <= '0;
    end else if (ena) begin
      case (state)
        ST_LOAD: begin
          case (load_idx)
            5'd0:  a_words[0][7:0]   <= ui_in;
            5'd1:  a_words[0][15:8]  <= ui_in;
            5'd2:  a_words[0][23:16] <= ui_in;
            5'd3:  a_words[0][31:24] <= ui_in;
            5'd4:  a_words[1][7:0]   <= ui_in;
            5'd5:  a_words[1][15:8]  <= ui_in;
            5'd6:  a_words[1][23:16] <= ui_in;
            5'd7:  a_words[1][31:24] <= ui_in;
            5'd8:  b_words[0][7:0]   <= ui_in;
            5'd9:  b_words[0][15:8]  <= ui_in;
            5'd10: b_words[0][23:16] <= ui_in;
            5'd11: b_words[0][31:24] <= ui_in;
            5'd12: b_words[1][7:0]   <= ui_in;
            5'd13: b_words[1][15:8]  <= ui_in;
            5'd14: b_words[1][23:16] <= ui_in;
            5'd15: b_words[1][31:24] <= ui_in;
            5'd16: c0_word[7:0]      <= ui_in;
            5'd17: c0_word[15:8]     <= ui_in;
            5'd18: c0_word[23:16]    <= ui_in;
            5'd19: c0_word[31:24]    <= ui_in;
            default: ;
          endcase

          if (load_idx == FRAME_LAST) begin
            state <= ST_RUN;
            run_count <= '0;
          end else begin
            load_idx <= load_idx + 5'd1;
          end
        end

        ST_RUN: begin
          if (run_count == (RUN_LATENCY_CYCLES - 3'd1)) begin
            result_word <= core_r;
            state <= ST_OUT;
            out_idx <= '0;
          end else begin
            run_count <= run_count + 3'd1;
          end
        end

        ST_OUT: begin
          if (out_idx == 2'd3) begin
            state <= ST_LOAD;
            load_idx <= '0;
            a_words[0] <= '0;
            a_words[1] <= '0;
            b_words[0] <= '0;
            b_words[1] <= '0;
            c0_word <= '0;
          end else begin
            out_idx <= out_idx + 2'd1;
          end
        end

        default: begin
          state <= ST_LOAD;
          load_idx <= '0;
          run_count <= '0;
          out_idx <= '0;
        end
      endcase
    end
  end

  always @(*) begin
    if (state == ST_OUT) begin
      case (out_idx)
        2'd0: uo_out = result_word[7:0];
        2'd1: uo_out = result_word[15:8];
        2'd2: uo_out = result_word[23:16];
        2'd3: uo_out = result_word[31:24];
        default: uo_out = 8'h00;
      endcase
    end else begin
      uo_out = 8'h00;
    end
  end

  assign uio_out = 8'h00;
  assign uio_oe  = 8'h00;

  wire _unused = &{uio_in, 1'b0};

endmodule
// Generated by CIRCT 30ab7a85a
module fpmult_loop_muladd_s3fdp(
  input              clk,
                     reset,
  input  [1:0][31:0] a,
                     b,
                     c,
  input              clk_0,
  output [31:0]      r
);

  wire [31:0] _GEN;
  wire [31:0] _GEN_0;
  wire [31:0] _GEN_1;
  wire        _GEN_2;
  wire [63:0] _GEN_3 = /*cast(bit[63:0])*/b;
  wire [63:0] _GEN_4 = /*cast(bit[63:0])*/a;
  reg  [31:0] c_mem[0:1];
  always_ff @(posedge clk_0) begin
    if (reset) begin
    end
    else begin
      c_mem[1'h0] <= 32'h0;
      if (_GEN_2)
        c_mem[1'h0] <= _GEN_0;
    end
  end // always_ff @(posedge)
  reg  [31:0] _GEN_5;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_5 <= 32'h0;
    else
      _GEN_5 <= _GEN;
  end // always_ff @(posedge)
  assign _GEN_2 = _GEN_5 == 32'h0;
  reg  [31:0] _GEN_6;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_6 <= 32'h0;
    else
      _GEN_6 <= _GEN_1;
  end // always_ff @(posedge)
  wire        _GEN_7 = _GEN_6 == 32'h1;
  assign _GEN_1 = _GEN_2 ? (_GEN_7 ? 32'h0 : _GEN_6 + 32'h1) : _GEN_6;
  wire [31:0] _GEN_8 = _GEN_6[0] ? _GEN_4[63:32] : _GEN_4[31:0];
  wire [31:0] _GEN_9 = _GEN_6[0] ? _GEN_3[63:32] : _GEN_3[31:0];
  wire        _GEN_10 = _GEN_8[30:23] == 8'h0;
  wire        _GEN_11 = &(_GEN_8[30:23]);
  wire        _GEN_12 = _GEN_8[22:0] == 23'h0;
  wire [22:0] _GEN_13 = _GEN_10 & _GEN_8[22] ? {_GEN_8[21:0], 1'h0} : _GEN_8[22:0];
  wire [1:0]  _GEN_14 =
    _GEN_10 & ~(_GEN_8[22])
      ? 2'h0
      : _GEN_11 & _GEN_12 ? 2'h2 : {_GEN_11 & ~_GEN_12, 1'h1};
  wire [33:0] _GEN_15 = {_GEN_14, _GEN_8[31:23], _GEN_13};
  wire        _GEN_16 = _GEN_9[30:23] == 8'h0;
  wire        _GEN_17 = &(_GEN_9[30:23]);
  wire        _GEN_18 = _GEN_9[22:0] == 23'h0;
  wire [22:0] _GEN_19 = _GEN_16 & _GEN_9[22] ? {_GEN_9[21:0], 1'h0} : _GEN_9[22:0];
  wire [1:0]  _GEN_20 =
    _GEN_16 & ~(_GEN_9[22])
      ? 2'h0
      : _GEN_17 & _GEN_18 ? 2'h2 : {_GEN_17 & ~_GEN_18, 1'h1};
  wire [33:0] _GEN_21 = {_GEN_20, _GEN_9[31:23], _GEN_19};
  wire        _GEN_22 =
    {_GEN_14, _GEN_8[30:23], _GEN_13} < {_GEN_20, _GEN_9[30:23], _GEN_19};
  wire [7:0]  _GEN_23 =
    _GEN_22 ? _GEN_9[30:23] - _GEN_8[30:23] : _GEN_8[30:23] - _GEN_9[30:23];
  wire [33:0] _GEN_24 = _GEN_22 ? _GEN_21 : _GEN_15;
  wire [33:0] _GEN_25 = _GEN_22 ? _GEN_15 : _GEN_21;
  wire        _GEN_26 = _GEN_24[31] ^ _GEN_25[31];
  wire [5:0]  _GEN_27 = {_GEN_24[31], _GEN_25[31], _GEN_24[33:32], _GEN_25[33:32]};
  wire [23:0] _GEN_28 = _GEN_25[33:32] == 2'h0 ? 24'h0 : {1'h1, _GEN_25[22:0]};
  wire        _GEN_29 = _GEN_27 == 6'h10;
  wire        _GEN_30 = _GEN_27 == 6'h20;
  wire [1:0]  _GEN_31 =
    _GEN_27 == 6'h3A | _GEN_27 == 6'hA | _GEN_27 == 6'h8 | _GEN_27 == 6'h18
    | _GEN_27 == 6'h28 | _GEN_27 == 6'h38 | _GEN_27 == 6'h2 | _GEN_27 == 6'h12
    | _GEN_27 == 6'h22 | _GEN_27 == 6'h32 | _GEN_27 == 6'h9 | _GEN_27 == 6'h19
    | _GEN_27 == 6'h29 | _GEN_27 == 6'h39 | _GEN_27 == 6'h6 | _GEN_27 == 6'h16
    | _GEN_27 == 6'h26 | _GEN_27 == 6'h36
      ? 2'h2
      : _GEN_27 == 6'h5 | _GEN_27 == 6'h15 | _GEN_27 == 6'h25 | _GEN_27 == 6'h35
        | _GEN_27 == 6'h4 | _GEN_27 == 6'h14 | _GEN_27 == 6'h24 | _GEN_27 == 6'h34
        | _GEN_27 == 6'h1 | _GEN_27 == 6'h11 | _GEN_27 == 6'h21 | _GEN_27 == 6'h31
          ? 2'h1
          : _GEN_27 == 6'h0 | _GEN_29 | _GEN_30 | _GEN_27 == 6'h30 ? 2'h0 : 2'h3;
  wire [4:0]  _GEN_32 = _GEN_23 > 8'h19 ? 5'h1A : _GEN_23[4:0];
  wire [25:0] _GEN_33 = _GEN_32[4] ? {16'h0, _GEN_28[23:14]} : {_GEN_28, 2'h0};
  wire [25:0] _GEN_34 = _GEN_32[3] ? {8'h0, _GEN_33[25:8]} : _GEN_33;
  wire [25:0] _GEN_35 = _GEN_32[2] ? {4'h0, _GEN_34[25:4]} : _GEN_34;
  wire [25:0] _GEN_36 = _GEN_32[1] ? {2'h0, _GEN_35[25:2]} : _GEN_35;
  wire        _GEN_37 =
    _GEN_32[4] & (|(_GEN_28[13:0])) | _GEN_32[3] & (|(_GEN_33[7:0])) | _GEN_32[2]
    & (|(_GEN_34[3:0])) | _GEN_32[1] & (|(_GEN_35[1:0])) | _GEN_32[0] & _GEN_36[0];
  wire [26:0] _GEN_38 =
    {2'h1, _GEN_24[22:0], 2'h0}
    + ({1'h0, _GEN_32[0] ? {1'h0, _GEN_36[25:1]} : _GEN_36} ^ {27{_GEN_26}})
    + {26'h0, _GEN_26 & ~_GEN_37};
  wire        _GEN_39 = _GEN_38[26:11] == 16'h0;
  wire [27:0] _GEN_40 = _GEN_39 ? {_GEN_38[10:0], _GEN_37, 16'h0} : {_GEN_38, _GEN_37};
  wire        _GEN_41 = _GEN_40[27:20] == 8'h0;
  wire [27:0] _GEN_42 = _GEN_41 ? {_GEN_40[19:0], 8'h0} : _GEN_40;
  wire        _GEN_43 = _GEN_42[27:24] == 4'h0;
  wire [27:0] _GEN_44 = _GEN_43 ? {_GEN_42[23:0], 4'h0} : _GEN_42;
  wire        _GEN_45 = _GEN_44[27:26] == 2'h0;
  wire [27:0] _GEN_46 = _GEN_45 ? {_GEN_44[25:0], 2'h0} : _GEN_44;
  wire        _GEN_47 = ~(_GEN_46[27]);
  wire [26:0] _GEN_48 = _GEN_47 ? {_GEN_46[25:0], 1'h0} : _GEN_46[26:0];
  wire        _GEN_49 = &{_GEN_39, _GEN_41, _GEN_43, _GEN_45, _GEN_47};
  wire        _GEN_50 = _GEN_48[2] | _GEN_48[1] | _GEN_48[0];
  wire [33:0] _GEN_51 =
    {{1'h0, {1'h0, _GEN_24[30:23]} + 9'h1}
       - {5'h0, _GEN_39, _GEN_41, _GEN_43, _GEN_45, _GEN_47},
     _GEN_48[26:3]} + {33'h0, _GEN_48[3] & _GEN_50 | _GEN_48[3] & ~_GEN_50 & _GEN_48[4]};
  wire [3:0]  _GEN_52 = {_GEN_51[33:32], _GEN_31};
  wire [1:0]  _GEN_53 =
    _GEN_49 & _GEN_26 & _GEN_31 != 2'h3
      ? 2'h0
      : _GEN_52 == 4'h2 | _GEN_52 == 4'h6 | _GEN_52 == 4'hA | _GEN_52 == 4'hE
        | _GEN_52 == 4'h5
          ? 2'h2
          : _GEN_52 == 4'h1
              ? 2'h1
              : _GEN_52 == 4'h0 | _GEN_52 == 4'h4 | _GEN_52 == 4'h8 | _GEN_52 == 4'hC
                | _GEN_52 == 4'h9 | _GEN_52 == 4'hD
                  ? 2'h0
                  : 2'h3;
  wire        _GEN_54 = _GEN_53 == 2'h0;
  wire        _GEN_55 = _GEN_53 == 2'h1;
  wire [22:0] _GEN_56 =
    _GEN_54
      ? 23'h0
      : _GEN_51[31:24] == 8'h0 & _GEN_55
          ? {1'h1, _GEN_51[23:2]}
          : _GEN_55 ? _GEN_51[23:1] : {22'h0, _GEN_53[0]};
  wire [7:0]  _GEN_57 = _GEN_54 ? 8'h0 : _GEN_55 ? _GEN_51[31:24] : 8'hFF;
  wire [47:0] _GEN_58 = {25'h1, _GEN_13} * {25'h1, _GEN_19};
  wire [9:0]  _GEN_59 =
    {2'h0, _GEN_8[30:23]} + {2'h0, _GEN_9[30:23]} + {9'h0, _GEN_58[47]} - 10'h7F;
  wire [3:0]  _GEN_60 = {_GEN_14, _GEN_20};
  wire [1:0]  _GEN_61 =
    _GEN_60 == 4'h6 | _GEN_60 == 4'h9 | _GEN_60 == 4'hA
      ? 2'h2
      : _GEN_60 == 4'h5
          ? 2'h1
          : _GEN_60 == 4'h0 | _GEN_60 == 4'h1 | _GEN_60 == 4'h4 ? 2'h0 : 2'h3;
  wire [1:0]  _GEN_62 =
    _GEN_61 == 2'h1
      ? (_GEN_59[9:8] == 2'h2 | (&(_GEN_59[9:8]))
           ? 2'h0
           : _GEN_59[9:8] == 2'h1 ? 2'h2 : {|(_GEN_59[9:8]), 1'h1})
      : _GEN_61;
  wire [46:0] _GEN_63 = _GEN_58[47] ? _GEN_58[46:0] : {_GEN_58[45:0], 1'h0};
  wire        _GEN_64 = _GEN_62 == 2'h0;
  wire        _GEN_65 = _GEN_62 == 2'h1;
  wire [46:0] _GEN_66 = _GEN_59[7:0] == 8'h0 & _GEN_65 ? {1'h1, _GEN_63[46:1]} : _GEN_63;
  wire [30:0] _GEN_67 =
    {_GEN_59[7:0], _GEN_66[46:24]}
    + {30'h0, _GEN_66[23] & ((|(_GEN_66[22:0])) | _GEN_66[24])};
  wire [22:0] _GEN_68 = _GEN_64 ? 23'h0 : _GEN_65 ? _GEN_67[22:0] : {22'h0, _GEN_62[0]};
  wire [7:0]  _GEN_69 = _GEN_64 ? 8'h0 : _GEN_65 ? _GEN_67[30:23] : 8'hFF;
  wire        _GEN_70 = _GEN_57 == 8'h0;
  wire        _GEN_71 = &_GEN_57;
  wire        _GEN_72 = _GEN_56 == 23'h0;
  wire        _GEN_73 = _GEN_69 == 8'h0;
  wire        _GEN_74 = &_GEN_69;
  wire        _GEN_75 = _GEN_68 == 23'h0;
  wire [47:0] _GEN_76 =
    {25'h1, _GEN_70 & _GEN_56[22] ? {_GEN_56[21:0], 1'h0} : _GEN_56}
    * {25'h1, _GEN_73 & _GEN_68[22] ? {_GEN_68[21:0], 1'h0} : _GEN_68};
  wire [9:0]  _GEN_77 = {2'h0, _GEN_57} + {2'h0, _GEN_69} + {9'h0, _GEN_76[47]} - 10'h7F;
  wire [3:0]  _GEN_78 =
    {_GEN_70 & ~(_GEN_56[22])
       ? 2'h0
       : _GEN_71 & _GEN_72 ? 2'h2 : {_GEN_71 & ~_GEN_72, 1'h1},
     _GEN_73 & ~(_GEN_68[22])
       ? 2'h0
       : _GEN_74 & _GEN_75 ? 2'h2 : {_GEN_74 & ~_GEN_75, 1'h1}};
  wire [1:0]  _GEN_79 =
    _GEN_78 == 4'h6 | _GEN_78 == 4'h9 | _GEN_78 == 4'hA
      ? 2'h2
      : _GEN_78 == 4'h5
          ? 2'h1
          : _GEN_78 == 4'h0 | _GEN_78 == 4'h1 | _GEN_78 == 4'h4 ? 2'h0 : 2'h3;
  wire [1:0]  _GEN_80 =
    _GEN_79 == 2'h1
      ? (_GEN_77[9:8] == 2'h2 | (&(_GEN_77[9:8]))
           ? 2'h0
           : _GEN_77[9:8] == 2'h1 ? 2'h2 : {|(_GEN_77[9:8]), 1'h1})
      : _GEN_79;
  wire [46:0] _GEN_81 = _GEN_76[47] ? _GEN_76[46:0] : {_GEN_76[45:0], 1'h0};
  wire        _GEN_82 = _GEN_80 == 2'h0;
  wire        _GEN_83 = _GEN_80 == 2'h1;
  wire [46:0] _GEN_84 = _GEN_77[7:0] == 8'h0 & _GEN_83 ? {1'h1, _GEN_81[46:1]} : _GEN_81;
  wire [30:0] _GEN_85 =
    {_GEN_77[7:0], _GEN_84[46:24]}
    + {30'h0, _GEN_84[23] & ((|(_GEN_84[22:0])) | _GEN_84[24])};
  wire [22:0] _GEN_86 = _GEN_82 ? 23'h0 : _GEN_83 ? _GEN_85[22:0] : {22'h0, _GEN_80[0]};
  wire [7:0]  _GEN_87 = _GEN_82 ? 8'h0 : _GEN_83 ? _GEN_85[30:23] : 8'hFF;
  wire        _GEN_88 = c_mem[1'h0][30:23] == 8'h0;
  wire        _GEN_89 = &(c_mem[1'h0][30:23]);
  wire        _GEN_90 = c_mem[1'h0][22:0] == 23'h0;
  wire [22:0] _GEN_91 =
    _GEN_88 & c_mem[1'h0][22] ? {c_mem[1'h0][21:0], 1'h0} : c_mem[1'h0][22:0];
  wire [1:0]  _GEN_92 =
    _GEN_88 & ~(c_mem[1'h0][22])
      ? 2'h0
      : _GEN_89 & _GEN_90 ? 2'h2 : {_GEN_89 & ~_GEN_90, 1'h1};
  wire [33:0] _GEN_93 = {_GEN_92, c_mem[1'h0][31:23], _GEN_91};
  wire        _GEN_94 = _GEN_87 == 8'h0;
  wire        _GEN_95 = &_GEN_87;
  wire        _GEN_96 = _GEN_86 == 23'h0;
  wire [22:0] _GEN_97 = _GEN_94 & _GEN_86[22] ? {_GEN_86[21:0], 1'h0} : _GEN_86;
  wire [1:0]  _GEN_98 =
    _GEN_94 & ~(_GEN_86[22])
      ? 2'h0
      : _GEN_95 & _GEN_96 ? 2'h2 : {_GEN_95 & ~_GEN_96, 1'h1};
  wire [33:0] _GEN_99 =
    {_GEN_98,
     (_GEN_83 | _GEN_80 == 2'h2 | _GEN_82)
       & ((_GEN_55 | _GEN_53 == 2'h2 | _GEN_54) & ~(_GEN_49 & _GEN_26)
          & ~(_GEN_30 | _GEN_29) & _GEN_24[31] ^ (_GEN_65 | _GEN_62 == 2'h2 | _GEN_64)
          & (_GEN_8[31] ^ _GEN_9[31])),
     _GEN_87,
     _GEN_97};
  wire        _GEN_100 =
    {_GEN_92, c_mem[1'h0][30:23], _GEN_91} < {_GEN_98, _GEN_87, _GEN_97};
  wire [7:0]  _GEN_101 =
    _GEN_100 ? _GEN_87 - c_mem[1'h0][30:23] : c_mem[1'h0][30:23] - _GEN_87;
  wire [33:0] _GEN_102 = _GEN_100 ? _GEN_99 : _GEN_93;
  wire [33:0] _GEN_103 = _GEN_100 ? _GEN_93 : _GEN_99;
  wire        _GEN_104 = _GEN_102[31] ^ _GEN_103[31];
  wire [5:0]  _GEN_105 = {_GEN_102[31], _GEN_103[31], _GEN_102[33:32], _GEN_103[33:32]};
  wire [23:0] _GEN_106 = _GEN_103[33:32] == 2'h0 ? 24'h0 : {1'h1, _GEN_103[22:0]};
  wire        _GEN_107 = _GEN_105 == 6'h10;
  wire        _GEN_108 = _GEN_105 == 6'h20;
  wire [1:0]  _GEN_109 =
    _GEN_105 == 6'h3A | _GEN_105 == 6'hA | _GEN_105 == 6'h8 | _GEN_105 == 6'h18
    | _GEN_105 == 6'h28 | _GEN_105 == 6'h38 | _GEN_105 == 6'h2 | _GEN_105 == 6'h12
    | _GEN_105 == 6'h22 | _GEN_105 == 6'h32 | _GEN_105 == 6'h9 | _GEN_105 == 6'h19
    | _GEN_105 == 6'h29 | _GEN_105 == 6'h39 | _GEN_105 == 6'h6 | _GEN_105 == 6'h16
    | _GEN_105 == 6'h26 | _GEN_105 == 6'h36
      ? 2'h2
      : _GEN_105 == 6'h5 | _GEN_105 == 6'h15 | _GEN_105 == 6'h25 | _GEN_105 == 6'h35
        | _GEN_105 == 6'h4 | _GEN_105 == 6'h14 | _GEN_105 == 6'h24 | _GEN_105 == 6'h34
        | _GEN_105 == 6'h1 | _GEN_105 == 6'h11 | _GEN_105 == 6'h21 | _GEN_105 == 6'h31
          ? 2'h1
          : _GEN_105 == 6'h0 | _GEN_107 | _GEN_108 | _GEN_105 == 6'h30 ? 2'h0 : 2'h3;
  wire [4:0]  _GEN_110 = _GEN_101 > 8'h19 ? 5'h1A : _GEN_101[4:0];
  wire [25:0] _GEN_111 = _GEN_110[4] ? {16'h0, _GEN_106[23:14]} : {_GEN_106, 2'h0};
  wire [25:0] _GEN_112 = _GEN_110[3] ? {8'h0, _GEN_111[25:8]} : _GEN_111;
  wire [25:0] _GEN_113 = _GEN_110[2] ? {4'h0, _GEN_112[25:4]} : _GEN_112;
  wire [25:0] _GEN_114 = _GEN_110[1] ? {2'h0, _GEN_113[25:2]} : _GEN_113;
  wire        _GEN_115 =
    _GEN_110[4] & (|(_GEN_106[13:0])) | _GEN_110[3] & (|(_GEN_111[7:0])) | _GEN_110[2]
    & (|(_GEN_112[3:0])) | _GEN_110[1] & (|(_GEN_113[1:0])) | _GEN_110[0] & _GEN_114[0];
  wire [26:0] _GEN_116 =
    {2'h1, _GEN_102[22:0], 2'h0}
    + ({1'h0, _GEN_110[0] ? {1'h0, _GEN_114[25:1]} : _GEN_114} ^ {27{_GEN_104}})
    + {26'h0, _GEN_104 & ~_GEN_115};
  wire        _GEN_117 = _GEN_116[26:11] == 16'h0;
  wire [27:0] _GEN_118 =
    _GEN_117 ? {_GEN_116[10:0], _GEN_115, 16'h0} : {_GEN_116, _GEN_115};
  wire        _GEN_119 = _GEN_118[27:20] == 8'h0;
  wire [27:0] _GEN_120 = _GEN_119 ? {_GEN_118[19:0], 8'h0} : _GEN_118;
  wire        _GEN_121 = _GEN_120[27:24] == 4'h0;
  wire [27:0] _GEN_122 = _GEN_121 ? {_GEN_120[23:0], 4'h0} : _GEN_120;
  wire        _GEN_123 = _GEN_122[27:26] == 2'h0;
  wire [27:0] _GEN_124 = _GEN_123 ? {_GEN_122[25:0], 2'h0} : _GEN_122;
  wire        _GEN_125 = ~(_GEN_124[27]);
  wire [26:0] _GEN_126 = _GEN_125 ? {_GEN_124[25:0], 1'h0} : _GEN_124[26:0];
  wire        _GEN_127 = &{_GEN_117, _GEN_119, _GEN_121, _GEN_123, _GEN_125};
  wire        _GEN_128 = _GEN_126[2] | _GEN_126[1] | _GEN_126[0];
  wire [33:0] _GEN_129 =
    {{1'h0, {1'h0, _GEN_102[30:23]} + 9'h1}
       - {5'h0, _GEN_117, _GEN_119, _GEN_121, _GEN_123, _GEN_125},
     _GEN_126[26:3]}
    + {33'h0, _GEN_126[3] & _GEN_128 | _GEN_126[3] & ~_GEN_128 & _GEN_126[4]};
  wire [3:0]  _GEN_130 = {_GEN_129[33:32], _GEN_109};
  wire [1:0]  _GEN_131 =
    _GEN_127 & _GEN_104 & _GEN_109 != 2'h3
      ? 2'h0
      : _GEN_130 == 4'h2 | _GEN_130 == 4'h6 | _GEN_130 == 4'hA | _GEN_130 == 4'hE
        | _GEN_130 == 4'h5
          ? 2'h2
          : _GEN_130 == 4'h1
              ? 2'h1
              : _GEN_130 == 4'h0 | _GEN_130 == 4'h4 | _GEN_130 == 4'h8 | _GEN_130 == 4'hC
                | _GEN_130 == 4'h9 | _GEN_130 == 4'hD
                  ? 2'h0
                  : 2'h3;
  wire        _GEN_132 = _GEN_131 == 2'h0;
  wire        _GEN_133 = _GEN_131 == 2'h1;
  assign _GEN_0 =
    {(_GEN_133 | _GEN_131 == 2'h2 | _GEN_132) & ~(_GEN_127 & _GEN_104)
       & ~(_GEN_108 | _GEN_107) & _GEN_102[31],
     _GEN_132 ? 8'h0 : _GEN_133 ? _GEN_129[31:24] : 8'hFF,
     _GEN_132
       ? 23'h0
       : _GEN_129[31:24] == 8'h0 & _GEN_133
           ? {1'h1, _GEN_129[23:2]}
           : _GEN_133 ? _GEN_129[23:1] : {22'h0, _GEN_131[0]}};
  assign _GEN = _GEN_2 & _GEN_7 ? 32'h0 : _GEN_5;
  assign r = c_mem[1'h0];
endmodule

